# Generated by Django 5.0.4 on 2024-05-27 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adminusername', models.CharField(max_length=20)),
                ('adminemail', models.EmailField(max_length=254)),
                ('adminpassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AdminStudent',
            fields=[
                ('adminstudentregister', models.IntegerField(primary_key=True, serialize=False)),
                ('adminstudentname', models.CharField(max_length=20)),
                ('adminstudentclass', models.CharField(max_length=20)),
                ('adminstudentsem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminTeacher',
            fields=[
                ('TeacherId', models.IntegerField(primary_key=True, serialize=False)),
                ('TeacherName', models.CharField(max_length=20)),
                ('TeacherSubject', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='AdminClassList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=20)),
                ('classRoom', models.CharField(max_length=20)),
                ('classTeacher', models.OneToOneField(default='Teacher Name', on_delete=django.db.models.deletion.CASCADE, to='application.adminteacher')),
            ],
            options={
                'verbose_name': 'Class Teacher List',
                'ordering': ['classTeacher'],
            },
        ),
        migrations.CreateModel(
            name='TakeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.DateTimeField(blank=True, default=None, null=True)),
                ('present', models.BooleanField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.adminstudent')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.adminteacher')),
            ],
        ),
    ]
