# Generated by Django 5.0.4 on 2024-05-28 07:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('dates', models.DateField(default=datetime.date.today)),
                ('full_day', models.BooleanField()),
                ('accept', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.adminstudent')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.adminteacher')),
            ],
        ),
    ]
